const fs = require('fs')
const diacritics = require('diacritics')
const textoEntrada = fs.readFileSync('entrada.txt', 'utf-8')
console.log("Texto original: ",textoEntrada)
const textoSalida = textoEntrada.toLowerCase()
console.log("Texto modificado: ",textoSalida)
const textoNormalizado = diacritics.remove(textoSalida)
console.log("Texto sin acentos y en minúsculas ",textoNormalizado)
fs.writeFileSync('salida.txt', textoNormalizado)
console.log("El texto modificado se ha guardado en salida.txt")